### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by vinisalazar**
Hi Kevin,

If merged this PR will:

- rename the main package folder (from bin/ to vegeta/)
- add a setup.py and an \_\_init\_\_.py file (allow pip install)
- quick fix to imports
- small edits to README

Hope it helps!

V

### CODE REVIEW

**Comment by klamkiew** [comment]
Looks good, was on my stack anyway but didn't manage to find the time to do it. Was actually supposed to be done with #7 though :) Will look through it in more detail and merge it asap.

**Comment by vinisalazar** [comment]
I'll try to give a go at #7

**Comment by klamkiew** [comment]
Don't do this (yet), please. I am currently refactoring a lot of the pipeline and splitting some functionalities into another git repo. So there will be some major changes here in the next weeks and it would be a shame if you'd put much effort in it now. But it is obv. appreciated! :)

**Comment by vinisalazar** [comment]
Sure, thanks for the heads-up

**Review by klamkiew — APPROVED** [review]

**Pull request merged**
